source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'buybid_common', path: '../buybid_common'
gem 'buybid_rpc', path: '../buybid_rpc'

gemspec
