# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: markets.proto for package 'rpc'

require 'grpc'

module Rpc
  module Markets
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rpc.Markets'

      rpc :search_product_cards, SearchProductCardsReq, SearchProductCardsResp
      rpc :get_product_detail, GetProductDetailReq, GetProductDetailResp
      rpc :parse_link, ParseLinkReq, ParseLinkResp
    end

    Stub = Service.rpc_stub_class
  end
end
