# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: markets.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("markets.proto", :syntax => :proto3) do
    add_message "rpc.SearchProductCardsReq" do
      optional :buybid_market_name, :string, 1
      optional :page_index, :int32, 2
      optional :page_size, :int32, 3
      optional :filters, :string, 4
    end
    add_message "rpc.SearchProductCardsResp" do
      optional :buybid_market_name, :string, 1
      optional :page_index, :int32, 2
      optional :page_next, :int32, 3
      optional :page_size, :int32, 4
      optional :filters, :string, 5
      repeated :products, :message, 6, "rpc.Product"
      repeated :sellers, :message, 7, "rpc.Seller"
    end
    add_message "rpc.GetProductDetailReq" do
      optional :buybid_market_name, :string, 1
      optional :product_id, :string, 2
    end
    add_message "rpc.GetProductDetailResp" do
      optional :buybid_market_name, :string, 1
      optional :product_id, :string, 2
      optional :product, :message, 3, "rpc.Product"
    end
    add_message "rpc.ParseLinkReq" do
      optional :buybid_market_name, :string, 1
      optional :link_url, :string, 2
    end
    add_message "rpc.ParseLinkResp" do
      optional :buybid_market_name, :string, 1
      optional :link_url, :string, 2
      optional :link_home_url, :string, 3
      map :data, :string, :string, 4
    end
    add_message "rpc.Seller" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :rating_point, :string, 3
      optional :rating_url, :string, 4
      optional :popular, :string, 5
    end
    add_message "rpc.ProductAttributes" do
      optional :buybid_market_name, :string, 1
      optional :name, :string, 2
      optional :description, :string, 3
      optional :available_on, :int64, 4
      optional :tax_category_id, :int32, 5
      optional :price, :string, 6
      optional :currency, :string, 7
      optional :shipping_category_id, :int32, 8
      optional :meta_title, :string, 9
      optional :meta_keywords, :string, 10
      optional :meta_description, :string, 11
      repeated :tag_list, :string, 12
    end
    add_message "rpc.ProductProperty" do
      optional :name, :string, 1
      optional :value, :string, 2
    end
    add_message "rpc.ProductOptionValue" do
      optional :name, :string, 1
      optional :value, :string, 2
    end
    add_message "rpc.Product" do
      optional :buybid_market_name, :string, 1
      optional :image_url, :string, 2
      optional :attributes, :message, 3, "rpc.ProductAttributes"
      repeated :buybid_category_ids, :int32, 4
      repeated :properties, :message, 5, "rpc.ProductProperty"
      repeated :option_values, :message, 6, "rpc.ProductOptionValue"
    end
  end
end

module Rpc
  SearchProductCardsReq = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.SearchProductCardsReq").msgclass
  SearchProductCardsResp = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.SearchProductCardsResp").msgclass
  GetProductDetailReq = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetProductDetailReq").msgclass
  GetProductDetailResp = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetProductDetailResp").msgclass
  ParseLinkReq = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.ParseLinkReq").msgclass
  ParseLinkResp = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.ParseLinkResp").msgclass
  Seller = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.Seller").msgclass
  ProductAttributes = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.ProductAttributes").msgclass
  ProductProperty = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.ProductProperty").msgclass
  ProductOptionValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.ProductOptionValue").msgclass
  Product = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.Product").msgclass
end
